[package]
name = "flinch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
tokio = { version="1.27.0", features=["full"] }
crossbeam-queue = "0.3.8"
dashmap = { version="5.4.0", features=["rayon", "serde"] }
rayon = "1.7.0"
serde = { version="1.0.159", features=["derive"] }
serde_json = "1.0.95"
chrono = "0.4.24"
lazy_static = "1.4.0"
thiserror = "1.0.40"
uuid = { version="1.3.1", features = ["v4","fast-rng","macro-diagnostics"] }