[package]
name = "flinch"
version = "0.1.4"
edition = "2021"
authors = ["Mohammad Julfikar <julfikar@eztech.com.my>", "Mohammad Julfikar <md.julfikar.mahmud@gmail.com>"]
categories = ["parser-implementations","caching","database-implementations"]
description = "flinch in-memory database"
exclude = [
    ".idea",
    ".github"
]
keywords = ["flql","flinch","dql","database","ram","in-memory","in memory","caching"]
license = "Apache-2.0"
repository = "https://github.com/mjm918/flinch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
evalexpr = { version="9.0.0", features=["serde_support","regex_support"] }
futures = "0.3.28"
flql = "0.1.4"
tokio = { version="1.27.0", features=["full"] }
crossbeam-queue = "0.3.8"
dashmap = { version="5.4.0", features=["rayon", "serde"] }
rayon = "1.7.0"
serde = { version="1.0.160", features=["derive"] }
serde_json = "1.0.95"
chrono = "0.4.24"
thiserror = "1.0.40"
uuid = { version="1.3.1", features = ["v4","fast-rng","macro-diagnostics"] }