name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Yay! 🎉 That was your first issue. Thank you for helping us to improve flinch"
        pr-message: "Wow! 😱 It wouldn't be possible without you"
